# Use pathways module?
usepathways: true
# Use Climate module?
useclimate: true
# Use deterioration module?
usedeterioration: true
# Use Creatures module?
usecreatures: true
# Use Burn module?
useburn: true
# Use Vegetation module?
usevegetation: true
# Probabilities of changing a block:
pathways:
  probabilities:
    grass-dirt: 0.1
    dirt-coarse: 0.05
    coarse-gravel: 0.25
    gravel-cobble: 0.12
    cobble-cblstairs: 0.002
    cblstairs-cblslab: 0.001
  multilpliers:
    sneaking: 0
    walking: 1
    sprinting: 2
    horse: 4
deteriorate:
  probabilities:
    stonebrick-cracked: 0.002
    smoothdiorite-diorite: 0.003
    smoothgranite-granite: 0.003
    smoothandesite-andesite: 0.003