name: LivelyWorld
main: com.kylantraynor.livelyworld.LivelyWorld
version: 0.0.3
depend: [ProtocolLib, DraggyData, Dynmap]
commands:
  livelyworld:
    description: Access all livelyworld commands.
    permission: livelyworld.all
    aliases: [lw]